export const SET_YEAR = 'SET_YEAR';

export const DOWNLOAD_PHOTOS_START = 'DOWNLOAD_PHOTOS_START';
export const DOWNLOAD_PHOTOS_SUCCESS = 'DOWNLOAD_PHOTOS_SUCCESS';
export const DOWNLOAD_PHOTOS_ERROR = 'DOWNLOAD_PHOTOS_ERROR';